import { openai } from "./client";

import { tools } from "./tools";

import { toolmap } from "../tools/toolmap";

export async function getAIResponse(
  userMessages: any[]
) {
  const messages: any[] = [
    {
      role: "system",

      content: `
      You are an intelligent HR leave assistant.

      Rules:

      - If user wants leave,
        always use createLeave tool

      - If user mentions travel/trip/vacation,
        use Vacation Leave

      - If user mentions sick/fever,
        use Sick Leave

      - If no leave type,
        use Casual Leave

      - After leave creation,
        ask if user wants OOO

      - If user confirms,
        ask:
        1. autogenerated
        2. custom

      - Use scheduleOOO tool
        only after collecting
        all information
      `,
    },

    ...userMessages,
  ];

  // FIRST CALL
  const completion =
    await openai.chat.completions.create({
      model: "gpt-4.1-mini",

      messages,

      tools,
    });

  const assistantMessage =
    completion.choices[0].message;

  messages.push(assistantMessage);

  // TOOL EXECUTION
  if (assistantMessage.tool_calls) {
    for (const toolCall of assistantMessage.tool_calls) {
      if (!('function' in toolCall) || toolCall.type !== 'function') {
        continue;
      }

      const functionName = toolCall.function.name;

      const functionArgs = toolCall.function.arguments
        ? JSON.parse(toolCall.function.arguments)
        : undefined;

      const toolFunction =
        toolmap[
          functionName as keyof typeof toolmap
        ];

      const toolResult = await toolFunction(functionArgs);

      messages.push({
        role: "tool",

        tool_call_id: toolCall.id,

        content: JSON.stringify(toolResult),
      });
    }

    // SECOND CALL
    const finalResponse =
      await openai.chat.completions.create({
        model: "gpt-4.1-mini",

        messages,
      });

    return finalResponse
      .choices[0].message;
  }

  return assistantMessage;
}